# Generated by Django 4.1.5 on 2023-02-01 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField(max_length=255)),
                ('Status', models.CharField(choices=[('open/notdone', 'open/notdone'), ('done', 'done')], default='open/notdone', max_length=100, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Assigned_To', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
