# Generated by Django 4.1.5 on 2023-02-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('open/notdone', 'open/notdone'), ('done', 'done')], default='open/notdone', max_length=100),
        ),
    ]
